"use client";

import {
  LineChart,
  Clock,
  Car,
  MonitorSmartphone,
  Settings,
  CreditCard,
  Headphones,
  MessageSquare,
  User,
  Calendar,
  Mail,
  Phone,
  MapPin,
  Globe,
  Lock,
  Unlock,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Eye,
  EyeOff,
  Search,
  Filter,
  Edit,
  Trash,
  Plus,
  Minus,
  Check,
  X,
  Download,
  Upload,
  Share,
  Link,
  Copy,
  Bookmark,
  Tag,
  Folder,
  File,
  Image,
  Video,
  Music,
  Play,
  Pause,
  Volume,
  VolumeX,
  Sun,
  Moon,
  Bell,
  AlertCircle,
  Info,
} from "lucide-react";

export const iconMap: { [key: string]: React.ReactNode } = {
  LineChart: <LineChart />,
  Clock: <Clock />,
  Car: <Car />,
  MonitorSmartphone: <MonitorSmartphone />,
  Settings: <Settings />,
  CreditCard: <CreditCard />,
  MessageSquare: <MessageSquare />,
  Headphones: <Headphones />,
  User: <User />,
  Mail: <Mail />,
  Phone: <Phone />,
  MapPin: <MapPin />,
  Globe: <Globe />,
  Lock: <Lock />,
  Unlock: <Unlock />,
  Star: <Star />,
  Heart: <Heart />,
  ThumbsUp: <ThumbsUp />,
  ThumbsDown: <ThumbsDown />,
  Eye: <Eye />,
  EyeOff: <EyeOff />,
  Search: <Search />,
  Filter: <Filter />,
  Edit: <Edit />,
  Trash: <Trash />,
  Plus: <Plus />,
  Minus: <Minus />,
  Check: <Check />,
  X: <X />,
  Download: <Download />,
  Upload: <Upload />,
  Share: <Share />,
  Link: <Link />,
  Copy: <Copy />,
  Bookmark: <Bookmark />,
  Tag: <Tag />,
  Folder: <Folder />,
  File: <File />,
  Image: <Image />,
  Video: <Video />,
  Music: <Music />,
  Play: <Play />,
  Pause: <Pause />,
  Volume: <Volume />,
  VolumeX: <VolumeX />,
  Sun: <Sun />,
  Moon: <Moon />,
  Bell: <Bell />,
  AlertCircle: <AlertCircle />,
  Info: <Info />,
};